name: "Auto-Approve Version PRs"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  approve-and-merge:
    if: startsWith(github.event.pull_request.head.ref, 'version-update-')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      checks: write
      statuses: write

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Debug PR info
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Head Ref: ${{ github.event.pull_request.head.ref }}"
          echo "Base Ref: ${{ github.event.pull_request.base.ref }}"
          echo "Node ID: ${{ github.event.pull_request.node_id }}"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge PR
        run: |
          # Wait briefly to ensure GitHub registers the approval
          sleep 5
          gh pr merge ${{ github.event.pull_request.number }} \
            --squash \
            --admin \
            --delete-branch \
            --body "Automatically merged: Version bump [skip ci]"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}