name: "Auto-Merge Version PRs"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

jobs:
  approve-and-merge:
    if: startsWith(github.event.pull_request.head.ref, 'version-update-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto-approve PR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh pr review ${{ github.event.pull_request.number }} --approve --body "Automatically approved: Version bump"

      - name: Enable auto-merge
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash

      - name: Check mergeability status
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.pull_request.number }}
            });
            if (pr.mergeable_state !== 'clean') {
              core.setFailed(`PR not ready to merge. Status: ${pr.mergeable_state}`);
            }