name: "Auto-Create Version PR"

on:
  workflow_run:
    workflows: ["Deploy Todo App"]
    types:
      - completed

jobs:
  create-version-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Find version-update branch
        id: find_branch
        run: |
          # Fetch all remote branches
          git fetch --all
          # Find the most recent version-update branch
          BRANCH_NAME=$(git branch -r | grep 'origin/version-update-' | sort -r | head -1 | sed 's/origin\///' | tr -d ' ')
          echo "branch_name=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          echo "Found branch: ${BRANCH_NAME}"

      - name: Create Pull Request
        if: steps.find_branch.outputs.branch_name != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .
          branch: ${{ steps.find_branch.outputs.branch_name }}
          base: main
          title: "Version bump $(date +'%Y-%m-%d')"
          body: "Automated version update"
          labels: "automated"
          commit-message: "Version bump $(date +'%Y-%m-%d')"
          delete-branch: false
          draft: false