name: "Auto-Approve Version PRs"

on:
  pull_request:
    types: [opened, reopened]
    branches: [main]

jobs:
  approve-and-merge:
    if: startsWith(github.event.pull_request.head.ref, 'version-update-')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Approve PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
              body: 'Automatically approved: Version bump'
            })

      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          script: |
            github.graphql(`
              mutation {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: context.payload.pull_request.node_id,
                  mergeMethod: SQUASH
                }) {
                  clientMutationId
                }
              }
            `)