name: Auto PR for version updates

on:
  create:

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr:
    if: startsWith(github.ref_name, 'version-update-')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          base: main  # Change if needed
          title: "Auto PR for ${{ github.ref_name }}"
          body: "This PR was automatically created for the version update branch: ${{ github.ref_name }}."
          draft: false
